spring:
  application:
    name: crawler
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: server
    import: classpath:html-crawling-urls.yml

---
spring:
  config:
    activate:
      on-profile: test
    import: classpath:html-crawling-urls.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:goods
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/*.xml